routes/web.php
<?php

//frontend
Route::get('/', 'HomeController@index');
Route::get('/about', 'HomeController@about');
Route::get('/produk/{slug?}', 'HomeController@produk');
Route::get('/artikel/{slug?}', 'HomeController@artikel');
Route::get('/cara-belanja', 'HomeController@caraBelanja');
Route::get('/kontak', 'HomeController@kontak');

Route::group(['prefix'=>'admin', 'middleware'=>['auth', 'role:administrator']], function()
{
  Route::get('dashboard', 'HomeController@index');
  Route::resource('artikel', 'ArtikelController');
  Route::resource('user', 'UserController');
  Route::resource('statis', 'StatisController');
  Route::resource('banner', 'BannerController');
  Route::resource('slideshow', 'SlideshowController');
  Route::resource('produk', 'ProdukController');
  Route::resource('kategori', 'KategoriController');
  Route::resource('identitas', 'IdentitasController');
});

Auth::routes();
Route::get('/home', 'HomeController@index');

//VIEW
View::composer(['frontend', 'frontend.sidebar'], function($view){
  $view->kategoriproduk = App\Kategori::all();
  $view->identitas = App\Identitas::where('id',1)->first();
});

resources/views/backend.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html>
<head>
    <meta charset="UTF-8">
    <title>{{ $page_title or "AdminLTE Dashboard" }}</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{{ asset('bower_components/admin-lte/bootstrap/css/bootstrap.min.css') }}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{ asset('bower_components/admin-lte/dist/css/AdminLTE.min.css') }}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{ asset('bower_components/admin-lte/dist/css/skins/_all-skins.min.css') }}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{ asset('bower_components/admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body class="skin-blue">
<div class="wrapper">

    <!-- Header -->
    @include('header')

    <!-- Sidebar -->
    @include('sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                {{ $page_title or "Page Title" }}
                <small>{{ $page_description or null }}</small>
            </h1>
            <!-- You can dynamically generate breadcrumbs here -->
            <ol class="breadcrumb">
                <li><a href="{{ url('/statis') }}"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">{{ isset($page_title) ? $page_title : 'Halaman Admin' }}</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">
            <!-- Your Page Content Here -->
            @yield('content')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    <!-- Footer -->
    @include('footer')

</div><!-- ./wrapper -->

<!-- REQUIRED JS SCRIPTS -->

<!-- jQuery 2.2.3 -->
<script src="{{ url('bower_components/admin-lte/plugins/jQuery/jquery-2.2.3.min.js') }}"></script>
<!-- Bootstrap 3.3.6 -->
<script src="{{ url('bower_components/admin-lte/bootstrap/js/bootstrap.min.js') }}"></script>
<!-- FastClick -->
<script src="{{ url('bower_components/admin-lte/plugins/fastclick/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ url('bower_components/admin-lte/dist/js/app.min.js') }}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ url('bower_components/admin-lte/dist/js/demo.js') }}"></script>

<!-- Bootstrap WYSIHTML5 -->
<script src="{{ url('bower_components/admin-lte/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>

</body>
</html>

resources/views/dashboard.blade.php
@extends('backend')
@section('content')
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Dashboard</h3>
    </div>
    <div class="panel-body">
      <h3>Dashboard</h3>
    </div>
    <div class="panel-footer">

    </div>
  </div>
@endsection

resources/views/footer.blade.php
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
        Support by: <b><a href="https://facebook.com/marsonosaputro">Marsono Saputro</a></b>
    </div>
    <!-- Default to the left -->
    <strong>Copyright © 2017 <a href="#">Marsono Saputro</a>.</strong> All rights reserved.
</footer>

resources/views/frontend.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="robots" content="all,follow">
    <meta name="googlebot" content="index,follow,snippet,archive">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="{{ $identitas->description }}">
    <meta name="author" content="{{ $identitas->author }}">
    <meta name="keywords" content="{{ $identitas->keyword }}">

    <title>
        {{ isset($page_title) ? $page_title : $identitas->title }}
    </title>

    <link href='http://fonts.googleapis.com/css?family=Roboto:400,500,700,300,100' rel='stylesheet' type='text/css'>

    <!-- styles -->
    <link href="{{ asset('frontend/css/font-awesome.css') }}" rel="stylesheet">
    <link href="{{ asset('frontend/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('frontend/css/animate.min.css') }}" rel="stylesheet">
    <link href="{{ asset('frontend/css/owl.carousel.css') }}" rel="stylesheet">
    <link href="{{ asset('frontend/css/owl.theme.css') }}" rel="stylesheet">

    <!-- theme stylesheet -->
    <link href="{{ asset('frontend/css/style.default.css') }}" rel="stylesheet" id="theme-stylesheet">

    <!-- your stylesheet with modifications -->
    <link href="{{ asset('frontend/css/custom.css') }}" rel="stylesheet">

    <script src="{{ asset('frontend/js/respond.min.js') }}"></script>
    <script src="https://use.fontawesome.com/3f23df9e0b.js"></script>

    <link rel="shortcut icon" href="{{ asset('frontend/favicon.png') }}">



</head>

<body>

    <!-- *** TOPBAR ***
 _________________________________________________________ -->
    <div id="top">
        <div class="container">
            <div class="col-md-6 offer" data-animate="fadeInDown">
                <a href="{{ url('wellcome') }}" class="btn btn-success btn-sm" data-animate-hover="shake">Selamat Datang!</a>  <a href="{{ url('gallery-produk') }}">Dapatkan produk berkualitas di toko kami.</a>
            </div>
            <div class="col-md-6" data-animate="fadeInDown">
                <ul class="menu">
                  @if(Auth::check())
                    <li><a href="{{ url('/logout') }}" >Logout</a></li>
                    <li><a href="{{ url('/user/cart/account') }}">Area Pelanggan</a></li>
                  @else
                    <li><a href="#" data-toggle="modal" data-target="#login-modal">Login</a></li>
                  @endif
                    <li><a href="{{ url('about') }}">Profil</a></li>
                    <li><a href="{{ url('cara-belanja') }}">Cara Belanja</a></li>

                    <li><a href="{{ url('kontak') }}">Kontak</a></li>
                </ul>
            </div>
        </div>
        <div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="Login" aria-hidden="true">
            <div class="modal-dialog modal-sm">

                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title" id="Login">Pelanggan Login</h4>
                    </div>
                    <div class="modal-body">
                        <form action="{{ url('/login') }}" method="post">
                          {{ csrf_field() }}
                          <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                              <label for="email">E-mail</label>

                              <div>
                                  <input id="email-modal"  type="email" class="form-control" name="email" value="{{ old('email') }}">

                                  @if ($errors->has('email'))
                                      <span class="help-block">
                                          <strong>{{ $errors->first('email') }}</strong>
                                      </span>
                                  @endif
                              </div>
                          </div>
                          <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                              <label for="password">Password</label>

                              <div>
                                  <input id="password-modal" type="password" class="form-control" name="password">

                                  @if ($errors->has('password'))
                                      <span class="help-block">
                                          <strong>{{ $errors->first('password') }}</strong>
                                      </span>
                                  @endif
                              </div>
                          </div>
                            <p class="text-center">
                                <button class="btn btn-primary"><i class="fa fa-sign-in"></i> Login</button>
                            </p>

                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>

    <!-- *** TOP BAR END *** -->

    <!-- *** NAVBAR ***
 _________________________________________________________ -->

    <div class="navbar navbar-default yamm" role="navigation" id="navbar">
        <div class="container">
            <div class="navbar-header">

                <a class="navbar-brand home" href="{{ url('/') }}" data-animate-hover="bounce">
                    <img src="{{ asset('frontend') }}/img/logo.png" alt="YunusSHOP" class="hidden-xs img img-responsive">
                    <img src="{{ asset('frontend') }}/img/logo.png" alt="YunusSHOP" class="img img-responsive visible-xs img img-responsive"><span class="sr-only">Helmi Herbal</span>
                </a>

                <div class="navbar-buttons">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation">
                      <span style="font-weight: bold;">MENU</span>
                        <span class="sr-only">Toggle navigation</span>
                        <i class="fa fa-align-justify"></i>
                    </button>
                </div>

            </div>
            <!--/.navbar-header -->

            <div class="navbar-collapse collapse" id="navigation">

                <ul class="nav navbar-nav navbar-left">
                    <li class="{{ Request::is('/') ? 'active' : '' }}"><a href="{{ url('/') }}">Home</a></li>
                    <li class="{{ Request::is('about') ? 'active' : '' }}"><a href="{{ url('/about') }}">Profil</a></li>
                    <li class="{{ Request::is('produk') ? 'active' : '' }}"><a href="{{ url('/produk') }}">Produk</a></li>
                    <li class="{{ Request::is('artikel') ? 'active' : '' }}"><a href="{{ url('/artikel') }}">Artikel</a></li>
                    <li class="{{ Request::is('cara-belanja') ? 'active' : '' }}"><a href="{{ url('/cara-belanja') }}">Cara Belanja</a></li>
                    <li class="{{ Request::is('kontak') ? 'active' : '' }}"><a href="{{ url('/kontak') }}">Kontak</a></li>
                    @if (Auth::check())
                      <li class="{{ Request::is('user/cart/account') ? 'active' : '' }}"><a href="{{ url('user/cart/account') }}">Area Pelanggan</a></li>
                    @endif
                </ul>

            </div>
            <!--/.nav-collapse -->

            <div class="navbar-buttons">

                <div class="navbar-collapse collapse right" id="basket-overview">
                    <a href="{{ url('/cart-content') }}" class="btn btn-primary navbar-btn"><i class="fa fa-shopping-cart"></i><span class="hidden-sm">{{ Cart::count() }} barang</span></a>
                </div>
                <!--/.nav-collapse -->

                <!--
                <div class="navbar-collapse collapse right" id="search-not-mobile">
                    <button type="button" class="btn navbar-btn btn-primary" data-toggle="collapse" data-target="#search">
                        <span class="sr-only">Toggle search</span>
                        <i class="fa fa-search"></i>
                    </button>
                </div>
              -->
            </div>

            <div class="collapse clearfix" id="search">

                <form class="navbar-form" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search">
                        <span class="input-group-btn">

			<button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>

		    </span>
                    </div>
                </form>

            </div>
            <!--/.nav-collapse -->

        </div>
        <!-- /.container -->
    </div>
    <!-- /#navbar -->

    <!-- *** NAVBAR END *** -->
    @yield('content')

        <!-- *** FOOTER ***
 _________________________________________________________ -->
        <div id="footer" data-animate="fadeInUp">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-6">
                        <h4>Halaman Informasi</h4>

                        <ul>
                            <li><a href="{{ url('/about') }}">Profil</a></li>
                            <li><a href="{{ url('/cara-belanja') }}">Cara Belanja</a></li>
                            <li><a href="{{ url('kontak') }}">Kontak</a></li>
                        </ul>

                        <hr>

                        <h4>Area Pelanggan</h4>

                        <ul>
                            <li><a href="#" data-toggle="modal" data-target="#login-modal">Login</a>
                            </li>

                        </ul>

                        <hr class="hidden-md hidden-lg hidden-sm">

                    </div>
                    <!-- /.col-md-3 -->

                    <div class="col-md-3 col-sm-6">

                        <h4>Kategori Produk</h4>

                        <ul>
                            @foreach ($kategoriproduk as $d)
                                <li><a href="{{ url('kategori-produk/'.$d->id.'/'.$d->seo) }}">{{ $d->judul }}</a></li>
                            @endforeach
                        </ul>
                        <hr class="hidden-md hidden-lg">

                    </div>
                    <!-- /.col-md-3 -->

                    <div class="col-md-3 col-sm-6">
                        <h4>Kategori Artikel</h4>
                        <ul>
                            <li>satu</li>
                            <li>dua</li>
                        </ul>


                    </div>
                    <!-- /.col-md-3 -->
                    <div class="col-md-3 col-sm-6">
                        <h4>Kontak Kami</h4>
                        <i class="fa fa-map-marker"></i> Alamat lengkap
                        <br><i class="fa fa-phone-square"></i> Nomor telephone
                        <br><i class="fa fa-tablet"></i> nomor HP
                        <br><i class="fa fa-whatsapp"></i> Whatsapp
                        <br><i class="fa fa-envelope"></i> email@gmail.com
                    <!-- /.col-md-3 -->

                </div>
                <!-- /.row -->

            </div>
            <!-- /.container -->
        </div>
        <!-- /#footer -->

        <!-- *** FOOTER END *** -->


        <!-- *** COPYRIGHT ***
 _________________________________________________________ -->
        <div id="copyright">
            <div class="container">
                <div class="col-md-6">
                    <p class="pull-left">© 2017 {{ $identitas->title }}</p>

                </div>
                <div class="col-md-6">
                    <p class="pull-right">Template by <a href="http://bootstrapious.com/e-commerce-templates">Bootstrapious</a> with support from <a href="https://kakusei.cz">Kakusei</a>
                        <!-- Not removing these links is part of the licence conditions of the template. Thanks for understanding :) -->
                    </p>
                </div>
            </div>
        </div>
        <!-- *** COPYRIGHT END *** -->



    </div>
    <!-- /#all -->
    <!-- *** SCRIPTS TO INCLUDE ***
 _________________________________________________________ -->
    <script src="{{ asset('frontend/js/jquery-1.11.0.min.js') }}"></script>
    <script src="{{ asset('frontend/js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('frontend/js/jquery.cookie.js') }}"></script>
    <script src="{{ asset('frontend/js/waypoints.min.js') }}"></script>
    <script src="{{ asset('frontend/js/modernizr.js') }}"></script>
    <script src="{{ asset('frontend/js/bootstrap-hover-dropdown.js') }}"></script>
    <script src="{{ asset('frontend/js/owl.carousel.min.js') }}"></script>
    <script src="{{ asset('frontend/js/front.js') }}"></script>

</body>
</html>

resources/views/header.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="{{ url('admin/dashboard') }}" class="logo"><b>Web</b> Admin</a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- Messages: style can be found in dropdown.less-->
                <li class="dropdown messages-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-envelope-o"></i>
                        <span class="label label-success">4</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 4 messages</li>
                        <li>
                            <!-- inner menu: contains the messages -->
                            <ul class="menu">
                                <li><!-- start message -->
                                    <a href="#">
                                        <div class="pull-left">
                                            <!-- User Image -->
                                            <img src="{{ asset("/bower_components/admin-lte/dist/img/user2-160x160.jpg") }}" class="img-circle" alt="User Image"/>
                                        </div>
                                        <!-- Message title and timestamp -->
                                        <h4>
                                            Support Team
                                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                                        </h4>
                                        <!-- The message -->
                                        <p>Why not buy a new awesome theme?</p>
                                    </a>
                                </li><!-- end message -->
                            </ul><!-- /.menu -->
                        </li>
                        <li class="footer"><a href="#">See All Messages</a></li>
                    </ul>
                </li><!-- /.messages-menu -->

                <!-- Notifications Menu -->
                <li class="dropdown notifications-menu">
                    <!-- Menu toggle button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="label label-warning">10</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 10 notifications</li>
                        <li>
                            <!-- Inner Menu: contains the notifications -->
                            <ul class="menu">
                                <li><!-- start notification -->
                                    <a href="#">
                                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                    </a>
                                </li><!-- end notification -->
                            </ul>
                        </li>
                        <li class="footer"><a href="#">View all</a></li>
                    </ul>
                </li>
                <!-- Tasks Menu -->
                <li class="dropdown tasks-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-flag-o"></i>
                        <span class="label label-danger">9</span>
                    </a>
                    <ul class="dropdown-menu">
                        <li class="header">You have 9 tasks</li>
                        <li>
                            <!-- Inner menu: contains the tasks -->
                            <ul class="menu">
                                <li><!-- Task item -->
                                    <a href="#">
                                        <!-- Task title and progress text -->
                                        <h3>
                                            Design some buttons
                                            <small class="pull-right">20%</small>
                                        </h3>
                                        <!-- The progress bar -->
                                        <div class="progress xs">
                                            <!-- Change the css width attribute to simulate progress -->
                                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                                <span class="sr-only">20% Complete</span>
                                            </div>
                                        </div>
                                    </a>
                                </li><!-- end task item -->
                            </ul>
                        </li>
                        <li class="footer">
                            <a href="#">View all tasks</a>
                        </li>
                    </ul>
                </li>
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{ asset("/bower_components/admin-lte/dist/img/user2-160x160.jpg") }}" class="user-image" alt="User Image"/>
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ (isset(Auth::user()->name)) ? Auth::user()->name : 'Admin' }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{ asset("/bower_components/admin-lte/dist/img/user2-160x160.jpg") }}" class="img-circle" alt="User Image" />
                            <p>
                                {{ (isset(Auth::user()->name)) ? Auth::user()->name : 'Admin' }}
                                <small>Member since {{ isset(Auth::user()->created_at) ? Auth::user()->created_at : '' }}</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            <div class="col-xs-4 text-center">
                                <a href="#">Followers</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Sales</a>
                            </div>
                            <div class="col-xs-4 text-center">
                                <a href="#">Friends</a>
                            </div>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ url('admin/logout') }}" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/navbartop.blade.php
<div class="col-md-12 no-padding">
    <div class="pull-right visible-lg">
        <ul id="hornavmenu" class="nav navbar-nav">
            <li>
                <a href="index.html" class="fa-home">Home</a>
            </li>
            <li>
                <span class="fa-gears">Kegiatan</span>
                <ul>
                    <li><a href="#">Seminar Keluarga</a></li>
                    <li><a href="#">Berita Talkshow</a></li>
                    <li><a href="#">Gallery Kegiatan</a></li>
                </ul>
            </li>
            <li>
                <span class="fa-copy">Pages</span>
                <ul>
                    <li><a href="#">Profil JKI</a></li>
                    <li><a href="#">Profil Kak AdhiPASTI</a></li>
                    <li><a href="pages-faq.html">F.A.Q.</a></li>
                    <li><a href="pages-about-me.html">About Me</a></li>
                </ul>
            </li>
            <li>
                <span class="fa-th">Testimony</span>
                <ul>
                    <li><a href="#">Seminar</a></li>
                    <li><a href="">TJB</a></li>
                </ul>
            </li>
            <li>
                <span class="fa-font">Berita</span>
                <ul>
                    <li>
                        <a href="blog-list.html">Blog</a>
                    </li>
                    <li>
                        <a href="blog-single.html">Blog Single Item</a>
                    </li>
                </ul>
            </li>
            <li>
                <a href="contact.html" class="fa-comment">Contact</a>
            </li>
        </ul>
    </div>
</div>

resources/views/sidebar.blade.php
<!-- Left side column. contains the sidebar -->
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset("/bower_components/admin-lte/dist/img/user2-160x160.jpg") }}" class="img-circle" alt="User Image" />
            </div>
            <div class="pull-left info">
                <p>{{ (isset(Auth::user()->name)) ? Auth::user()->name : 'Admin' }}</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <!-- search form (Optional) -->
        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
<span class="input-group-btn">
  <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
</span>
            </div>
        </form>
        <!-- /.search form -->

        <!-- Sidebar Menu -->
        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
            {{ csrf_field() }}
        </form>
        <ul class="sidebar-menu">
            <li class="header">HEADER</li>
            <!-- Optionally, you can add icons to the links -->
            <li><a href="{{ route('identitas.index') }}"><i class="fa fa-university"></i><span>Identitas Web</span></a></li>
            <li><a href="{{ route('artikel.index') }}"><i class="fa fa-font"></i><span>Artikel</span></a></li>
            <li><a href="{{ route('produk.index') }}"><i class="fa fa-gift"></i><span>Produk</span></a></li>
            <li><a href="{{ route('kategori.index') }}"><i class="fa fa-th"></i>Kategori Produk</a></li>
            <li><a href="{{ route('statis.index') }}"><i class="fa fa-tablet"></i>Statis</a></li>
            <li><a href="{{ route('slideshow.index') }}"><i class="fa fa-image"></i>Slideshow</a></li>
            <li><a href="{{ route('banner.index') }}"><i class="fa fa-desktop"></i>Banner</a></li>
            <li><a href="{{ route('user.index') }}"><i class="fa fa-users"></i><span>User</span></a></li>
            <li>
              <a href="{{ url('/logout') }}"
                onclick="event.preventDefault();
                         document.getElementById('logout-form').submit();">
                <i class="fa fa-sign-out"></i><span>Logout</span>
              </a>
            </li>
            <!--
            <li class="treeview">
                <a href="#"><span>Multilevel</span> <i class="fa fa-angle-left pull-right"></i></a>
                <ul class="treeview-menu">
                    <li><a href="#">Link in level 2</a></li>
                    <li><a href="#">Link in level 2</a></li>
                </ul>
            </li>
          -->
        </ul><!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>